#!/usr/bin/env python3
"""Download the pinned GTFS snapshot used by Romania Rail GTFS.

The GTFS files are generated by Vasile Coțovanu's open-source converter from
the annual Romanian passenger timetable published by Informatică Feroviară.
This script deliberately pins a Git commit and verifies SHA-256 checksums so a
rebuild does not silently change under the same project version.
"""
from __future__ import annotations

import hashlib
import json
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw" / "gtfs"
SOURCE = ROOT / "data" / "source.json"
SOURCE_SNAPSHOT = json.loads(SOURCE.read_text(encoding="utf-8"))["snapshot"]
COMMIT = SOURCE_SNAPSHOT["upstream_commit"]
BASE = f"https://raw.githubusercontent.com/vasile/data.gov.ro-gtfs-exporter/{COMMIT}/gtfs-out"
CHECKSUMS = SOURCE_SNAPSHOT["sha256"]


def digest(path: Path) -> str:
    hasher = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            hasher.update(block)
    return hasher.hexdigest()


def main() -> int:
    RAW.mkdir(parents=True, exist_ok=True)
    for name, expected in CHECKSUMS.items():
        target = RAW / name
        if target.exists() and digest(target) == expected:
            print(f"ok      {name}")
            continue
        url = f"{BASE}/{name}"
        print(f"fetch   {name}")
        try:
            with urllib.request.urlopen(url, timeout=60) as response, tempfile.NamedTemporaryFile(
                dir=RAW, delete=False
            ) as temporary:
                while block := response.read(1024 * 1024):
                    temporary.write(block)
                temporary_path = Path(temporary.name)
        except (urllib.error.URLError, TimeoutError) as exc:
            print(f"error   {name}: {exc}", file=sys.stderr)
            return 1
        actual = digest(temporary_path)
        if actual != expected:
            temporary_path.unlink(missing_ok=True)
            print(f"error   {name}: checksum {actual}, expected {expected}", file=sys.stderr)
            return 1
        temporary_path.replace(target)
    print(f"Pinned snapshot {COMMIT} is ready in {RAW}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
